# -*- coding: utf-8 -*-
"""practical 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BopeH-vt7i6ViPvLbajC7Z8e00cvnGZJ
"""

def heapify(arr, n, i):
    largest = i
    left = 2 * i + 1
    right = 2 * i + 2

    if left < n and arr[left] > arr[largest]:
        largest = left

    if right < n and arr[right] > arr[largest]:
        largest = right

    if largest != i:
        arr[i], arr[largest] = arr[largest], arr[i]
        heapify(arr, n, largest)


def heap_sort(arr):
    n = len(arr)

    for i in range(n // 2 - 1, -1, -1):
        heapify(arr, n, i)

    for i in range(n - 1, 0, -1):
        arr[0], arr[i] = arr[i], arr[0]

        heapify(arr, i, 0)


arr = [12, 11, 13, 5, 6, 7]

print("Original array:", arr)

heap_sort(arr)

print("Sorted array:", arr)